Drop MacOS build due to drop of Idris from homebrew
`brew install idris` resulsts in:

  Error: idris has been disabled because it is not maintained upstream!